In [3]:
import numpy as np
import time

In [8]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print('c',c)
print('Vectorized version:'+str(1000*(toc-tic))+'ms')

c = 0
tic = time.time()
for i in range (1000000):
    c+= a[i]*b[i]
toc = time.time()

print('c',c)
print('For Loop:',str(1000*(toc-tic))+'ms')

c 250248.9116557899
Vectorized version:1.3203620910644531ms
c 250248.91165579864
For Loop: 603.0945777893066ms


In [2]:
A = np.array([[56, 0, 4.4, 68],[1.2,104,52,8],[1.8, 135, 99, 0.9]])
print ('A:\n',A)

cal = A.sum(axis=0)
print ('\ncal',cal, '\n') 

percentage = 100*A/cal.reshape(1,4)
print (percentage)

A:
 [[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]

cal [ 59.  239.  155.4  76.9] 

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


## BroadCasting

In [10]:
B = np.array([1,2,3,4]).reshape(4,1)
print ('B',B)
C = B + 100
print ('\nC',C)

B = np.array([[1,2,3],[4,5,6]])
print ('\nB',B)
C = B + np.array([100, 200, 300])
print ('\nC',C)



B [[1]
 [2]
 [3]
 [4]]

C [[101]
 [102]
 [103]
 [104]]

B [[1 2 3]
 [4 5 6]]

C [[101 202 303]
 [104 205 306]]


## Python-Numpy Vectors

In [23]:
b = np.random.randn(5,1)
assert(b.shape == (5,1))

In [24]:
a = np.random.randn(5)
print ('a',a,'a.shape',a.shape)
b = np.random.randn(5,1)

print ('b',b,'b.shape',b.shape)

c = np.dot(b,b.T)
print('\nc',c,c.shape)


a [ 0.92477092  2.48845767 -2.71669732  1.50273627  0.09749212] a.shape (5,)
b [[ 0.27970721]
 [ 1.85779848]
 [-0.65420004]
 [ 1.84693778]
 [-1.06932263]] b.shape (5, 1)

c [[ 0.07823613  0.51963964 -0.18298447  0.51660182 -0.29909725]
 [ 0.51963964  3.4514152  -1.21537184  3.43123821 -1.98658596]
 [-0.18298447 -1.21537184  0.42797769 -1.20826676  0.6995509 ]
 [ 0.51660182  3.43123821 -1.20826676  3.41117916 -1.97497236]
 [-0.29909725 -1.98658596  0.6995509  -1.97497236  1.14345088]] (5, 5)
